### ISSUE TITLE
ISSUE FUNCTIONAL SPECIFICATION

### ISSUE THREAD

**Issue by habicll** [algosup/2024-2025-project-2-serious-game-team-3#1]
### Links : 

The following links redirect to the wrong website : 

- The current Godot link [Wikipedia](https://en.wikipedia.org/wiki/Godot) should be ( https://en.wikipedia.org/wiki/Godot_(game_engine) ). (l.211)

- The Solar energy link to return to the goal isn't working. (l.218)

- The Overview link doesn't work because the Overview doesn't exist. (l.5)

- The Goal / scope link doesn't work (l.8)

- The Gameplay mechanics, UI components, Player interactions links are not working. (l.13,14,15)

- The Win/Lose conditions link isn't working (l.20)

### Meaning : 

The following sentences could be rephrase or erase :

- Context -> " Current situation " = is the following sentence very useful to say ? : "This project is part of a seven-week educational program to evaluate both technical skills and understanding of sustainable practices. "

- To see : lose/win condition

**Comment by gderamchi** [comment]
I've fixed the issues.
I asked Franck about the problematic sentence, waiting for his answer.
Ok for win condition.
I'll see if an overview is useful or not.
