### ISSUE TITLE
ISSUE : FUNCTIONAL DOCUMENT

### ISSUE THREAD

**Issue by habicll** [algosup/2024-2025-project-2-serious-game-team-3#4]
### Link : 

- Definition link to wikipedia for building upgrade in the glossary (l.673)

- Definition link to wikipedia for dynamic challenges in the glossary (l.683)

### Meanings (Overall : explain more the features of the game):

- Don't add the level in the use cases, The users won't be able to select.

- In the PRIORITY OBJECTIVES you should say that the player will learn new things with our game (l.247)

- You said that we will have "10 unique buildings" but we are not sure about that (l.269)

-  I Don't understand the point of localization tools and Localization strategy as the mixed languages are in the futur improvement (l.607 and l.609)
 
### Misses :

-  There is a part with no text : Scope of work (l.232)
- weird implementation of win condition and lose condition (l.392 and l.407)

### Date

20/11/2024

### Reason for Update

Issues needs to be solve 

### Link : 

- Replace the link.
- Replace the link.

### Meanings :

- Remove this part.
- add a part to explain that the user will learn new things with our game.
- talk about this topic with the group and find a feature agreed by everybody.
- read this part again  and if there is no problem and that this part is relevant, then keep it else erase it.

### Mises :

- Fill the part
- Change the size of the sentence, instead of bullet points put a heading 2 or 3...

### Importance

2 - High Priority ❗

### Extra Field

- [x] I want to work on this issue

**Comment by gderamchi** [comment]
Done
