### ISSUE TITLE
ISSUE TECHNICAL SPECIFICATION

### ISSUE THREAD

**Issue by habicll** [algosup/2024-2025-project-2-serious-game-team-3#6]
### Description

Adding :

- I think you must talk about optimization of the game like strategies for optimizing performance, especially for larger city grids or complex simulations.

- maybe add a section on developing an in-game tutorial system to guide players through mechanics practices

- for me we must design a reward system with achievements for milestones (like the 5 years with low pollution) just to enhance player engagement so you have a concrete goal when you start the game, but I dont know if we will be able to do it since we dont have a lot lot of time 

- you must add comments into your code parts (//)

- Add a section on implementing dynamic weather (rain, fog) that change gameplay and pollution levels.

- maybe describe more how building animations or UI transitions will be handled to improve the visual experience.

- you didn't talk about the save/load game system.

I think you didn't talk enough with the dev team.

### Date

29/11/2024

### Reason for Update

Document too short in my opinion.

### Proposed Changes

Include the adding.

### Importance

2 - High Priority ❗

### Extra Field

- [ ] I want to work on this issue

**Comment by LucasAub** [comment]
Here's the modification required in this commit 0d35b0f6dd37a33ace2b731feac4c3bb07dbc3ad
